name: Auto-update grafana

on:
  schedule:
    # daily, hour and minute chosen arbitrarily
    - cron: "32 14 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Check latest grafana version from https://api.github.com/repos/grafana/grafana/
        id: check
        run: |
          # split lines to fail on exit != 0
          version="$(go run ./cmd/check-update/main.go)"
          echo "::set-output name=sha::${version%:*}"
          echo "::set-output name=tag::${version#*:}"

      - name: Fetch latest grafana
        if: steps.check.outputs.sha != ''
        id: fetch
        run: |
          git submodule update --init --depth=1 grafana-sources
          cd grafana-sources
          git fetch --depth=1 origin ${{steps.check.outputs.sha}}
          git checkout ${{steps.check.outputs.sha}}
          cd ..
          git diff --no-ext-diff

      - name: Compile latest grafana
        if: steps.check.outputs.sha != ''
        run: go run ./cmd/compile/main.go

      - name: Retrieve public files
        if: steps.check.outputs.sha != ''
        run: go run ./cmd/retrieve-public/main.go ${{steps.check.outputs.tag}}

      - name: Commit the new grafana
        if: steps.check.outputs.sha != ''
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: grafana ${{steps.check.outputs.tag}}
          tagging_message: v1.0.3-${{steps.check.outputs.tag}}
